#!/bin/bash

echo -n -e '\x4e\x45\x53\x1a\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' \
     > test.nes

./assembler --setpc 0 -o .romtmp test.s

cat .romtmp >> test.nes

fsize=`stat --printf="%s" .romtmp`

for i in `seq 1 $((32768 - $fsize))`; do
	echo -n -e '\x00' >> test.nes
done
