#!/bin/bash

romfile="test-1.chr"

echo > $romfile

echo -n -e '\x66' >> $romfile
echo -n -e '\x7f' >> $romfile
echo -n -e '\xff' >> $romfile
echo -n -e '\xff' >> $romfile
echo -n -e '\xff' >> $romfile
echo -n -e '\x7e' >> $romfile
echo -n -e '\x3c' >> $romfile
echo -n -e '\x18' >> $romfile

# echo -n -e '\x66' >> $romfile
# echo -n -e '\x5f' >> $romfile
# echo -n -e '\xbf' >> $romfile
# echo -n -e '\xbf' >> $romfile
# echo -n -e '\xff' >> $romfile
# echo -n -e '\x7e' >> $romfile
# echo -n -e '\x3c' >> $romfile
# echo -n -e '\x18' >> $romfile

echo -n -e '\x00' >> $romfile
echo -n -e '\x00' >> $romfile
echo -n -e '\x00' >> $romfile
echo -n -e '\x00' >> $romfile
echo -n -e '\x00' >> $romfile
echo -n -e '\x00' >> $romfile
echo -n -e '\x00' >> $romfile
echo -n -e '\x00' >> $romfile

# echo -n -e '\x3C' >> $romfile
# echo -n -e '\x3C' >> $romfile
# echo -n -e '\xC3' >> $romfile
# echo -n -e '\xC3' >> $romfile
# echo -n -e '\xC3' >> $romfile
# echo -n -e '\xC3' >> $romfile
# echo -n -e '\x3C' >> $romfile
# echo -n -e '\x3C' >> $romfile

# echo -n -e '\x00' >> $romfile
# echo -n -e '\x00' >> $romfile
# echo -n -e '\x00' >> $romfile
# echo -n -e '\x00' >> $romfile
# echo -n -e '\x00' >> $romfile
# echo -n -e '\x00' >> $romfile
# echo -n -e '\x00' >> $romfile
# echo -n -e '\x00' >> $romfile

echo -n -e '\xFC' >> $romfile
echo -n -e '\xFC' >> $romfile
echo -n -e '\xC0' >> $romfile
echo -n -e '\xF8' >> $romfile
echo -n -e '\xF8' >> $romfile
echo -n -e '\xC0' >> $romfile
echo -n -e '\xC0' >> $romfile
echo -n -e '\xC0' >> $romfile

echo -n -e '\x00' >> $romfile
echo -n -e '\x00' >> $romfile
echo -n -e '\x00' >> $romfile
echo -n -e '\x00' >> $romfile
echo -n -e '\x00' >> $romfile
echo -n -e '\x00' >> $romfile
echo -n -e '\x00' >> $romfile
echo -n -e '\x00' >> $romfile

fsize=`stat --printf="%s" $romfile`
for i in `seq 1 $((4096 - $fsize))`; do
	echo -n -e '\x00' >> $romfile
done
