#!/bin/bash

if [ $# -ne 1 ]; then
    echo "pass only dir name"
fi

let sum=0

# TODO fix this
function count() {
    for file in `ls -F $1`; do
        if [ -z `echo $file | grep "\.rs"` ]; then
            let sum=$sum+`count $1/$(echo $file | sed 's/\///')`
        else
            let sum=$sum+$(cat $1/$file | wc -l)
        fi
    done
    echo $sum
}

count $1
